const User=require("../models/userModel"),catchAsyncErrors=require("../utils/catchAsyncErrors"),AppError=require("../utils/appError"),filterObj=(s,...r)=>{const t={};return Object.keys(s).forEach((e=>{r.includes(e)&&(t[e]=s[e])})),t};exports.getAllUser=catchAsyncErrors((async(s,r,t)=>{const e=await User.find();r.status(200).json({message:"success",results:e.length,data:e})})),exports.updateCurrentUser=catchAsyncErrors((async(s,r,t)=>{s.body.password&&t(new AppError("You are not allowed update password in this route",401));const e=filterObj(s.body,"firstName","lastName"),a=await User.findByIdAndUpdate(s.user.id,e,{new:!0,runValidators:!0});r.status(200).json({status:"success",data:{user:a}})})),exports.deactivate=catchAsyncErrors((async(s,r,t)=>{await User.findByIdAndUpdate(s.user.id,{active:!1}),r.status(204).json({status:"success",data:null})}));